typography_spectrum: 0.45817
color:
  brandColors:
    - '#0e0301'
    - '#322d34'
    - '#5e5960'
    - '#6f81a7'
    - '#f7ebdb'
  brandStrength: 0
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: CG_Owl
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Guillaume Vanson Portfolio '
description: Digital Sculptor
purpose: []
