name: CG_Owl
favicon: null
layout_spectrum: 1
typography_spectrum: 0.45817
title: 'Guillaume Vanson Portfolio '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f2d2e'
    - '#405046'
    - '#b7a277'
    - '#907a55'
    - '#e8dbae'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
