name: CG_Owl
favicon: null
layout_spectrum: 0.49548
typography_spectrum: 0.45817
title: 'Guillaume Vanson Portfolio '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0301'
    - '#322d34'
    - '#5e5960'
    - '#6f81a7'
    - '#f7ebdb'
  brandStrength: 0
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
